baseurl = "https://conejoninja.github.io/home-docs/"
languageCode = "en-us"
title = "Home Automation project"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = ""


[params]
	# General information
	author = "conejoninja"
	description = "Home Automation system."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/conejoninja/home"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "conejoninja"
	email   = "conejo@conejo.me"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Devices"
	url    = "devices/"
	weight = 10

[[menu.main]]
	name   = "Protocol"
	url    = "protocol/"
	weight = 20

[[menu.main]]
	name   = "Dockers"
	url    = "dockers/"
	weight = 30

