db_path: /data/db

web_user: some_user
web_password: random_password
web_port: 8080

mqtt_server: mqtt.domain.tld
mqtt_port: 9001
mqtt_protocol: ws
mqtt_user: mqttuser
mqtt_password: mqttpassword
mqtt_client_id: webapi