db_path: /data/db

mqtt_server: mqtt.domain.tld
mqtt_port: 9001
mqtt_protocol: ws
mqtt_user: mqttuser
mqtt_password: mqttpassword
mqtt_client_id: logger

websocket_enabled: false
websocket_port: 8055

